import type { ThemeDefinition, ThemeId } from '@/types';

export const DEFAULT_THEME_ID: ThemeId = 'github-dark';

export const LIST: ThemeDefinition[] = [
  {
    id: 'github-light',
    label: 'GitHub Light',
    description: 'Light GitHub palette',
    markdownTheme: 'gitHub',
    codeTheme: 'github-light',
    colors: {
      accent: 'blue',
      border: 'blue',
      codeBorder: 'blue',
      command: 'blue',
      error: 'red',
      messageSystem: 'gray',
      modeAuto: 'magenta',
      modePlan: 'blue',
      modeSafe: 'green',
      model: 'blue',
      secondary: 'gray',
      status: 'cyan',
      warning: 'yellow',
    },
  },

  {
    id: 'github-dark',
    label: 'GitHub Dark',
    description: 'Dark GitHub palette',
    markdownTheme: 'gitHub',
    codeTheme: 'github-dark',
    colors: {
      accent: 'cyan',
      border: 'cyan',
      codeBorder: 'gray',
      command: 'cyan',
      error: 'red',
      messageSystem: 'gray',
      modeAuto: 'magenta',
      modePlan: 'blue',
      modeSafe: 'green',
      model: 'cyan',
      secondary: 'gray',
      status: 'cyan',
      warning: 'yellow',
    },
  },

  {
    id: 'nord',
    label: 'Nord',
    description: 'Cool nordic blues',
    markdownTheme: 'nord',
    codeTheme: 'nord',
    colors: {
      accent: 'cyan',
      border: 'blue',
      codeBorder: 'blue',
      command: 'cyan',
      error: 'red',
      messageSystem: 'gray',
      modeAuto: 'magenta',
      modePlan: 'blue',
      modeSafe: 'green',
      model: 'cyan',
      secondary: 'gray',
      status: 'blue',
      warning: 'yellow',
    },
  },

  {
    id: 'dracula',
    label: 'Dracula',
    description: 'Bright neon contrast',
    markdownTheme: 'dracula',
    codeTheme: 'dracula',
    colors: {
      accent: 'magenta',
      border: 'magenta',
      codeBorder: 'magenta',
      command: 'magenta',
      error: 'red',
      messageSystem: 'gray',
      modeAuto: 'yellow',
      modePlan: 'magenta',
      modeSafe: 'green',
      model: 'magenta',
      secondary: 'gray',
      status: 'cyan',
      warning: 'yellow',
    },
  },

  {
    id: 'solarized-light',
    label: 'Solarized Light',
    description: 'Warm light contrast',
    markdownTheme: 'solarized',
    codeTheme: 'solarized-light',
    colors: {
      accent: 'yellow',
      border: 'yellow',
      codeBorder: 'yellow',
      command: 'yellow',
      error: 'red',
      messageSystem: 'gray',
      modeAuto: 'cyan',
      modePlan: 'blue',
      modeSafe: 'green',
      model: 'yellow',
      secondary: 'gray',
      status: 'cyan',
      warning: 'yellow',
    },
  },

  {
    id: 'solarized-dark',
    label: 'Solarized Dark',
    description: 'Warm dark contrast',
    markdownTheme: 'solarized',
    codeTheme: 'solarized-dark',
    colors: {
      accent: 'yellow',
      border: 'yellow',
      codeBorder: 'yellow',
      command: 'yellow',
      error: 'red',
      messageSystem: 'gray',
      modeAuto: 'cyan',
      modePlan: 'blue',
      modeSafe: 'green',
      model: 'yellow',
      secondary: 'gray',
      status: 'cyan',
      warning: 'yellow',
    },
  },
] as const;

export function getTheme(themeId: ThemeId = DEFAULT_THEME_ID): ThemeDefinition {
  return LIST.find(({ id }) => id === themeId) ?? LIST[0];
}
